# Generated by Django 5.1.6 on 2025-02-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Указать сумму скидки в валюте заказа', max_digits=12, verbose_name='Размер скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену в валюте товара', max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('USD', 'Доллары США'), ('EUR', 'Евро'), ('RUB', 'Рубли')], default='RUB', max_length=3, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Процент, который будет добавлен к стоимости заказа', max_digits=5, verbose_name='Процент налога')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа в Stripe')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.discount', verbose_name='Скидка')),
                ('items', models.ManyToManyField(related_name='orders', to='payments.item', verbose_name='Товары')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.tax', verbose_name='Налог')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
